version: '3'
services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    ports:
    - "8080:8888"
    volumes:
    - .:/4D-Humans